package com.logistics.domain;

// Generated 2015-7-19 17:33:19 by Hibernate Tools 4.0.0

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private int cid;
	private String cname;

	public Company() {
	}

	public Company(int cid) {
		this.cid = cid;
	}

	public Company(int cid, String cname) {
		this.cid = cid;
		this.cname = cname;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

}
