package com.logistics.domain;

// Generated 2015-7-19 17:33:19 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Otherbill generated by hbm2java
 */
public class Otherbill implements java.io.Serializable {

	private int oid;
	private Date odate;
	private String ocompany;
	private String obiz;
	private String oquantity;
	private String oreason;
	private int oprofit;
	private String obroker;

	public Otherbill() {
	}

	public Otherbill(int oid, Date odate, int oprofit) {
		this.oid = oid;
		this.odate = odate;
		this.oprofit = oprofit;
	}

	public Otherbill(int oid, Date odate, String ocompany, String obiz,
			String oquantity, String oreason, int oprofit, String obroker) {
		this.oid = oid;
		this.odate = odate;
		this.ocompany = ocompany;
		this.obiz = obiz;
		this.oquantity = oquantity;
		this.oreason = oreason;
		this.oprofit = oprofit;
		this.obroker = obroker;
	}

	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	public Date getOdate() {
		return this.odate;
	}

	public void setOdate(Date odate) {
		this.odate = odate;
	}

	public String getOcompany() {
		return this.ocompany;
	}

	public void setOcompany(String ocompany) {
		this.ocompany = ocompany;
	}

	public String getObiz() {
		return this.obiz;
	}

	public void setObiz(String obiz) {
		this.obiz = obiz;
	}

	public String getOquantity() {
		return this.oquantity;
	}

	public void setOquantity(String oquantity) {
		this.oquantity = oquantity;
	}

	public String getOreason() {
		return this.oreason;
	}

	public void setOreason(String oreason) {
		this.oreason = oreason;
	}

	public int getOprofit() {
		return this.oprofit;
	}

	public void setOprofit(int oprofit) {
		this.oprofit = oprofit;
	}

	public String getObroker() {
		return this.obroker;
	}

	public void setObroker(String obroker) {
		this.obroker = obroker;
	}

}
