package com.logistics.domain;

// Generated 2015-7-19 17:33:19 by Hibernate Tools 4.0.0

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int rid;
	private String rname;

	public Role() {
	}

	public Role(int rid, String rname) {
		this.rid = rid;
		this.rname = rname;
	}

	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

}
