package com.logistics.domain;

import java.util.Date;

// Generated 2015-7-19 17:33:19 by Hibernate Tools 4.0.0

/**
 * Track generated by hbm2java
 */
public class Track implements java.io.Serializable {

	private int gid;
	private String glocation;
	private Date gdate;
	private String gno;
	private String orderno;
	
	
	public Track() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Track(int gid, String glocation, Date gdate, String gno,String orderno) {
		super();
		this.gid = gid;
		this.glocation = glocation;
		this.gdate = gdate;
		this.gno = gno;
		this.orderno = orderno;
	}
	public int getGid() {
		return gid;
	}
	public void setGid(int gid) {
		this.gid = gid;
	}
	public String getGlocation() {
		return glocation;
	}
	public void setGlocation(String glocation) {
		this.glocation = glocation;
	}
	public Date getGdate() {
		return gdate;
	}
	public void setGdate(Date gdate) {
		this.gdate = gdate;
	}
	public String getGno() {
		return gno;
	}
	public void setGno(String gno) {
		this.gno = gno;
	}
	public String getOrderno() {
		return orderno;
	}
	public void setOrderno(String orderno) {
		this.orderno = orderno;
	}
	
	
	

}
