package com.logistics.domain;

// Generated 2015-7-19 17:33:19 by Hibernate Tools 4.0.0

/**
 * Transport generated by hbm2java
 */
public class Transport implements java.io.Serializable {

	private int tid;
	private String tno;
	private String tname;
	private String taddr;
	private String tlxt;
	private String tlxdh;
	private String tchdh;
	private Double tprice;
	private Double tzxf;
	private Double tshf;
	private Double tthf;
	private Double tcbf;
	private String tthch;
	private String tthr;
	private String tsjdh;
	private String tthcb;
	private String tgsdh;

	public Transport() {
	}

	public Transport(int tid) {
		this.tid = tid;
	}

	public Transport(int tid, String tno, String tname, String taddr,
			String tlxt, String tlxdh, String tchdh, Double tprice,
			Double tzxf, Double tshf, Double tthf, Double tcbf,
			String tthch, String tthr, String tsjdh, String tthcb, String tgsdh) {
		this.tid = tid;
		this.tno = tno;
		this.tname = tname;
		this.taddr = taddr;
		this.tlxt = tlxt;
		this.tlxdh = tlxdh;
		this.tchdh = tchdh;
		this.tprice = tprice;
		this.tzxf = tzxf;
		this.tshf = tshf;
		this.tthf = tthf;
		this.tcbf = tcbf;
		this.tthch = tthch;
		this.tthr = tthr;
		this.tsjdh = tsjdh;
		this.tthcb = tthcb;
		this.tgsdh = tgsdh;
	}

	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	public String getTno() {
		return this.tno;
	}

	public void setTno(String tno) {
		this.tno = tno;
	}

	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public String getTaddr() {
		return this.taddr;
	}

	public void setTaddr(String taddr) {
		this.taddr = taddr;
	}

	public String getTlxt() {
		return this.tlxt;
	}

	public void setTlxt(String tlxt) {
		this.tlxt = tlxt;
	}

	public String getTlxdh() {
		return this.tlxdh;
	}

	public void setTlxdh(String tlxdh) {
		this.tlxdh = tlxdh;
	}

	public String getTchdh() {
		return this.tchdh;
	}

	public void setTchdh(String tchdh) {
		this.tchdh = tchdh;
	}

	public Double getTprice() {
		return this.tprice;
	}

	public void setTprice(Double tprice) {
		this.tprice = tprice;
	}

	public Double getTzxf() {
		return this.tzxf;
	}

	public void setTzxf(Double tzxf) {
		this.tzxf = tzxf;
	}

	public Double getTshf() {
		return this.tshf;
	}

	public void setTshf(Double tshf) {
		this.tshf = tshf;
	}

	public Double getTthf() {
		return this.tthf;
	}

	public void setTthf(Double tthf) {
		this.tthf = tthf;
	}

	public Double getTcbf() {
		return this.tcbf;
	}

	public void setTcbf(Double tcbf) {
		this.tcbf = tcbf;
	}

	public String getTthch() {
		return this.tthch;
	}

	public void setTthch(String tthch) {
		this.tthch = tthch;
	}

	public String getTthr() {
		return this.tthr;
	}

	public void setTthr(String tthr) {
		this.tthr = tthr;
	}

	public String getTsjdh() {
		return this.tsjdh;
	}

	public void setTsjdh(String tsjdh) {
		this.tsjdh = tsjdh;
	}

	public String getTthcb() {
		return this.tthcb;
	}

	public void setTthcb(String tthcb) {
		this.tthcb = tthcb;
	}

	public String getTgsdh() {
		return this.tgsdh;
	}

	public void setTgsdh(String tgsdh) {
		this.tgsdh = tgsdh;
	}

}
