package com.logistics.domain;

// Generated 2015-7-19 17:33:19 by Hibernate Tools 4.0.0

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int uid;
	private String uname;
	private String upassword;
	private Integer rid;

	public User() {
	}

	public User(int uid, String uname, String upassword) {
		this.uid = uid;
		this.uname = uname;
		this.upassword = upassword;
	}

	public User(int uid, String uname, String upassword, Integer rid) {
		this.uid = uid;
		this.uname = uname;
		this.upassword = upassword;
		this.rid = rid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpassword() {
		return this.upassword;
	}

	public void setUpassword(String upassword) {
		this.upassword = upassword;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

}
